

# load packages----
library(rhdf5) 
library(tidyverse) 
library(readr)
library(tximport) # package for getting Kallisto results into R
library(ensembldb) #helps deal with ensembl
library(EnsDb.Hsapiens.v86) 
library(datapasta) # great for copy and paste data into R environment. 
library(edgeR)
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(dplyr)

# read in  study design ----
#the readr package (from tidyverse) was used.
targets <- read_tsv("study_design_P3.tsv")
sampleLabels <- targets$sample

# we can easily create file paths to the abundance files generated by Kallisto using the 'file.path' function
path <- file.path(targets$sample, "abundance.tsv") # set file paths to your mapped data
# now check to make sure this path is correct by seeing if the files exist
all(file.exists(path)) 
#The all() function will return TRUE if every element in the logical vector is TRUE.

# get annotations using organism-specific package ----
Tx <- transcripts(EnsDb.Hsapiens.v86, columns=c("tx_id", "gene_name"))
Tx <- as_tibble(Tx)
#need to change first column name to 'target_id'
Tx <- dplyr::rename(Tx, target_id = tx_id)
#transcrip ID needs to be the first column in the dataframe
Tx <- dplyr::select(Tx, "target_id", "gene_name")

# import Kallisto transcript counts into R using Tximport ----
# copy the abundance files to the working directory and rename so that each sample has a unique name
Txi_gene <- tximport(path, type = "kallisto", tx2gene = Tx, 
                     countsFromAbundance = "lengthScaledTPM", ignoreTxVersion = T)

myTPM <- Txi_gene$abundance
myCounts <- Txi_gene$counts
colSums(myTPM)
colSums(myCounts)

myDGEList <- DGEList(myCounts)
# use the 'cpm' function from EdgeR to get counts per million
cpm <- cpm(myDGEList) 
colSums(cpm)
log2.cpm <- cpm(myDGEList, log=TRUE)
log2.cpm.df <- as_tibble(log2.cpm, rownames = "geneID")
log2.cpm.df
# add your sample names to this dataframe
colnames(log2.cpm.df) <- c("geneID", sampleLabels)
# Filter your data ----
#first, take a look at how many genes or transcripts have no read counts at all
table(rowSums(myDGEList$counts==0)==18)
keepers <- rowSums(cpm>1)>=3
# now use base R's simple subsetting method to filter your DGEList based on the logical produced above
myDGEList.filtered <- myDGEList[keepers,]
dim(myDGEList.filtered)
log2.cpm.filtered <- cpm(myDGEList.filtered, log=TRUE)
log2.cpm.filtered.df <- as_tibble(log2.cpm.filtered, rownames = "geneID")
colnames(log2.cpm.filtered.df) <- c("geneID", sampleLabels)
# Normalize your data ----
myDGEList.filtered.norm <- calcNormFactors(myDGEList.filtered, method = "TMM")
# use the 'cpm' function from EdgeR to get counts per million from your normalized data
log2.cpm.filtered.norm <- cpm(myDGEList.filtered.norm, log=TRUE)
log2.cpm.filtered.norm.df <- as_tibble(log2.cpm.filtered.norm, rownames = "geneID")
colnames(log2.cpm.filtered.norm.df) <- c("geneID", sampleLabels)
write_tsv(log2.cpm.filtered.norm.df, "log2.cpm.filtered.norm.df_PTEN_P5.tsv")
# Set up your design matrix ----
group <- factor(targets$group)
design <- model.matrix(~0 + group)
colnames(design) <- levels(group)

# Model mean-variance trend and fit linear model to data ----
# Use VOOM function from Limma package to model the mean-variance relationship
v.DEGList.filtered.norm <- voom(myDGEList.filtered.norm, design, plot = TRUE)
# fit a linear model to your data
fit <- lmFit(v.DEGList.filtered.norm, design)
# Contrast matrix ----
contrast.matrix <- makeContrasts(
  
  "Chap WT/I135L vs Chap WT/WT" = Chap_induction - Chap, #1
  "Chap KO/KO vs Chap WT/WT" = Chap_KO - Chap,  #2
  "Apex WT/I135L vs Apex WT/WT" = Apex - Apex_correction, #3
  "Apex KO/KO vs Apex WT/WT" = Apex_KO - Apex_correction, #4
  "Apex WT/WT vs Chap WT/WT" = Apex_correction - Chap, #5
  "Apex WT/I135L vs Chap WT/I135L" = Apex - Chap_induction, #6
  "Apex KO/KO vs Chap KO/KO" = Apex_KO - Chap_KO, #7
  
  levels=design)

# extract the linear model fit -----
fits <- contrasts.fit(fit, contrast.matrix)

ebFit <- eBayes(fits)

myTopHits <- topTable(ebFit, adjust ="BH", coef=1, number=40000, sort.by="logFC")
# convert to a tibble
myTopHits.df <- myTopHits %>%
  as_tibble(rownames = "geneID")
ranks_ac =  myTopHits.df$t
ranks_ac <- cbind(myTopHits.df$geneID, ranks_ac) 
colnames(ranks_ac) <- c("GeneName","rank")
#sort ranks in decreasing order
ranks_ac <- ranks_ac[order(as.numeric(ranks_ac[,2]),decreasing = TRUE),]
write.table(ranks_ac,file="ranks_p3_induction_vs_chap_t.rnk",col.name = TRUE, sep="\t", row.names = FALSE, quote = FALSE)


